wordLists = [
    {
        "listTitle": "Animals",
        "list": [
            "Lion",
            "Tiger",
            "Elephant",
            "Giraffe",
            "Kangaroo",
            "Zebra",
            "Penguin",
            "Dolphin",
            "Bear",
            "Shark",
            "Rabbit",
            "Panda",
            "Koala",
            "Wolf",
            "Fox",
            "Cheetah",
            "Horse",
            "Squirrel",
            "Eagle",
            "Owl",
            "Rhinoceros",
            "Hippopotamus",
            "Alligator",
            "Antelope",
            "Sloth"
        ]
    },
    {
        "listTitle": "Countries",
        "list": [
            "United States",
            "Canada",
            "Brazil",
            "United Kingdom",
            "France",
            "Germany",
            "Italy",
            "Russia",
            "China",
            "India",
            "Japan",
            "Australia",
            "Mexico",
            "South Africa",
            "Argentina",
            "Egypt",
            "Saudi Arabia",
            "Turkey",
            "Spain",
            "Sweden",
            "Norway",
            "Netherlands",
            "Belgium",
            "Switzerland",
            "Greece"
        ]
    },
    {
        "listTitle": "Movies",
        "list": [
            "The Godfather",
            "Titanic",
            "Inception",
            "The Dark Knight",
            "Forrest Gump",
            "Pulp Fiction",
            "Star Wars: A New Hope",
            "The Shawshank Redemption",
            "Jurassic Park",
            "The Matrix",
            "Avengers: Endgame",
            "Gladiator",
            "Harry Potter and the Sorcerer's Stone",
            "The Lord of the Rings: The Fellowship of the Ring",
            "Schindler's List",
            "Back to the Future",
            "The Lion King",
            "Fight Club",
            "Interstellar",
            "Frozen",
            "The Silence of the Lambs",
            "The Departed",
            "Goodfellas",
            "Avatar",
            "Jaws"
        ]
    },
    {
        "listTitle": "Sports",
        "list": [
            "Soccer",
            "Basketball",
            "Baseball",
            "Tennis",
            "Cricket",
            "Rugby",
            "Golf",
            "Swimming",
            "Volleyball",
            "American Football",
            "Ice Hockey",
            "Athletics",
            "Boxing",
            "Wrestling",
            "Cycling",
            "Table Tennis",
            "Field Hockey",
            "Lacrosse",
            "Motorsport",
            "Skiing",
            "Badminton",
            "Gymnastics",
            "Surfing",
            "Fencing",
            "Karate"
        ]
    },
    {
        "listTitle": "Fruits",
        "list": [
            "Apple",
            "Banana",
            "Orange",
            "Grapes",
            "Strawberry",
            "Pineapple",
            "Mango",
            "Cherry",
            "Blueberry",
            "Watermelon",
            "Peach",
            "Kiwi",
            "Raspberry",
            "Pomegranate",
            "Coconut",
            "Papaya",
            "Lemon",
            "Lime",
            "Avocado",
            "Fig",
            "Plum",
            "Nectarine",
            "Tangerine",
            "Blackberry",
            "Cantaloupe",
            "Honeydew"
        ]
    },
    {
        "listTitle": "Musical Instruments",
        "list": [
            "Guitar",
            "Piano",
            "Violin",
            "Drums",
            "Flute",
            "Saxophone",
            "Trumpet",
            "Cello",
            "Clarinet",
            "Trombone",
            "Harp",
            "Accordion",
            "Ukulele",
            "Bass",
            "Ocarina",
            "Banjo",
            "Marimba",
            "Synthesizer",
            "Bagpipes",
            "Mandolin",
            "Electric Guitar",
            "Keyboard",
            "French Horn",
            "Tuba",
            "Didgeridoo"
        ]
    },
    {
        "listTitle": "Colors",
        "list": [
            "Red",
            "Blue",
            "Green",
            "Yellow",
            "Orange",
            "Purple",
            "Pink",
            "Brown",
            "Black",
            "White",
            "Gray",
            "Cyan",
            "Magenta",
            "Turquoise",
            "Lavender",
            "Beige",
            "Coral",
            "Maroon",
            "Navy",
            "Olive",
            "Teal",
            "Crimson",
            "Peach",
            "Slate",
            "Emerald"
        ]
    },
    {
        "listTitle": "Books",
        "list": [
            "To Kill a Mockingbird",
            "1984",
            "Pride and Prejudice",
            "The Great Gatsby",
            "Moby-Dick",
            "War and Peace",
            "The Catcher in the Rye",
            "The Hobbit",
            "Harry Potter and the Sorcerer's Stone",
            "The Lord of the Rings",
            "Brave New World",
            "Fahrenheit 451",
            "The Chronicles of Narnia",
            "Animal Farm",
            "The Alchemist",
            "The Da Vinci Code",
            "The Kite Runner",
            "Jane Eyre",
            "The Grapes of Wrath",
            "The Picture of Dorian Gray",
            "The Fault in Our Stars",
            "Little Women",
            "The Secret Garden",
            "The Hunger Games",
            "The Outsiders"
        ]
    },
    {
        "listTitle": "Famous People",
        "list": [
            "Albert Einstein",
            "Marie Curie",
            "Martin Luther King Jr.",
            "Mahatma Gandhi",
            "Nelson Mandela",
            "William Shakespeare",
            "Leonardo da Vinci",
            "Amelia Earhart",
            "Coco Chanel",
            "Elvis Presley",
            "Oprah Winfrey",
            "Beyoncé",
            "Steve Jobs",
            "Winston Churchill",
            "Abraham Lincoln",
            "Mother Teresa",
            "Bill Gates",
            "Malala Yousafzai",
            "Michael Jordan",
            "Rosa Parks",
            "Jane Austen",
            "Cleopatra",
            "Florence Nightingale",
            "Mark Twain",
            "Vincent van Gogh"
        ]
    },
    {
        "listTitle": "Food",
        "list": [
            "Pizza",
            "Sushi",
            "Pasta",
            "Burger",
            "Tacos",
            "Salad",
            "Ice Cream",
            "Chocolate",
            "Rice",
            "Curry",
            "Steak",
            "Dumplings",
            "Sandwich",
            "Fries",
            "Pancakes",
            "Kebab",
            "Fish and Chips",
            "Quiche",
            "Noodles",
            "Cereal",
            "Fried Chicken",
            "Lasagna",
            "Chili",
            "Biryani",
            "Muffins"
        ]
    },
    {
        "listTitle": "Vehicles",
        "list": [
            "Car",
            "Bicycle",
            "Bus",
            "Motorcycle",
            "Truck",
            "Train",
            "Airplane",
            "Boat",
            "Helicopter",
            "Van",
            "Scooter",
            "Subway",
            "Tram",
            "Limo",
            "Golf Cart",
            "ATV",
            "Segway",
            "Tank",
            "Hot Air Balloon",
            "Jet Ski",
            "Rickshaw",
            "Motorhome",
            "Moped",
            "Cargo Ship",
            "Freight Train"
        ]
    },
    {
        "listTitle": "TV Shows",
        "list": [
            "Friends",
            "Breaking Bad",
            "Game of Thrones",
            "The Office",
            "Stranger Things",
            "The Simpsons",
            "The Big Bang Theory",
            "The Crown",
            "Grey's Anatomy",
            "Sherlock",
            "The Mandalorian",
            "Westworld",
            "Black Mirror",
            "Parks and Recreation",
            "Narcos",
            "The Walking Dead",
            "The Fresh Prince of Bel-Air",
            "Brooklyn Nine-Nine",
            "Better Call Saul",
            "Money Heist",
            "The Sopranos",
            "The Wire",
            "How I Met Your Mother",
            "The Twilight Zone",
            "Lost"
        ]
    },
    {
        "listTitle": "Cities",
        "list": [
            "New York",
            "Los Angeles",
            "Tokyo",
            "London",
            "Paris",
            "Sydney",
            "Berlin",
            "Dubai",
            "Rome",
            "Moscow",
            "Beijing",
            "Rio de Janeiro",
            "Mumbai",
            "Singapore",
            "Bangkok",
            "Toronto",
            "Istanbul",
            "San Francisco",
            "Seoul",
            "Cairo",
            "Barcelona",
            "Buenos Aires",
            "Lisbon",
            "Amsterdam",
            "Helsinki",
            "Vienna"
        ]
    },
    {
        "listTitle": "Flowers",
        "list": [
            "Rose",
            "Tulip",
            "Daisy",
            "Sunflower",
            "Lily",
            "Orchid",
            "Carnation",
            "Chrysanthemum",
            "Daffodil",
            "Hydrangea",
            "Iris",
            "Peony",
            "Jasmine",
            "Lavender",
            "Marigold",
            "Poppy",
            "Gardenia",
            "Geranium",
            "Zinnia",
            "Freesia",
            "Snapdragon",
            "Foxglove",
            "Petunia",
            "Violet",
            "Aster"
        ]
    },
    {
        "listTitle": "Inventions",
        "list": [
            "Telephone",
            "Light Bulb",
            "Internet",
            "Airplane",
            "Television",
            "Computer",
            "Radio",
            "Printing Press",
            "Penicillin",
            "Vaccination",
            "Steam Engine",
            "Refrigerator",
            "Camera",
            "Electricity",
            "Bicycle",
            "Sewing Machine",
            "Typewriter",
            "Calculator",
            "Microwave",
            "Dishwasher",
            "GPS",
            "Smartphone",
            "Toaster",
            "3D Printer",
            "Laser"
        ]
    },
    {
        "listTitle": "Jobs/Professions",
        "list": [
            "Doctor",
            "Engineer",
            "Teacher",
            "Nurse",
            "Scientist",
            "Lawyer",
            "Architect",
            "Artist",
            "Chef",
            "Mechanic",
            "Electrician",
            "Plumber",
            "Accountant",
            "Firefighter",
            "Police Officer",
            "Journalist",
            "Web Developer",
            "Pharmacist",
            "Veterinarian",
            "Carpenter",
            "Social Worker",
            "Graphic Designer",
            "Researcher",
            "Salesperson",
            "Business Analyst",
            "Massage Therapist"
        ]
    },
    {
        "listTitle": "Holidays",
        "list": [
            "Christmas",
            "Halloween",
            "New Year's Day",
            "Easter",
            "Valentine's Day",
            "Independence Day",
            "Hanukkah",
            "Diwali",
            "Ramadan",
            "Labor Day",
            "Memorial Day",
            "Veterans Day",
            "Groundhog Day",
            "Earth Day",
            "Midsummer",
            "Boxing Day",
            "Chinese New Year",
            "Bastille Day",
            "Oktoberfest",
            "Thanksgiving",
            "May Day",
            "National Day",
            "International Women's Day",
            "Father's Day",
            "Mother's Day",
            "Pride Month"
        ]
    },
    {
        "listTitle": "Historical Events",
        "list": [
            "World War I",
            "World War II",
            "The Great Depression",
            "Civil Rights Movement",
            "The Cold War",
            "The American Revolution",
            "The French Revolution",
            "The Moon Landing",
            "The Fall of the Berlin Wall",
            "The Renaissance",
            "The Industrial Revolution",
            "The Civil War",
            "The Vietnam War",
            "The Persian Gulf War",
            "9/11 Attacks",
            "The Signing of the Declaration of Independence",
            "The Abolition of Slavery",
            "The Discovery of America",
            "The Suffrage Movement",
            "The Invention of the Printing Press",
            "The Space Race",
            "The Cuban Missile Crisis",
            "The Korean War",
            "The Treaty of Versailles",
            "The Age of Enlightenment"
        ]
    },
    {
        "listTitle": "Clothing Items",
        "list": [
            "Shirt",
            "Pants",
            "Dress",
            "Skirt",
            "Suit",
            "Jacket",
            "Shoes",
            "Hat",
            "Scarf",
            "Belt",
            "Socks",
            "Coat",
            "Shorts",
            "Sweater",
            "T-shirt",
            "Jeans",
            "Blouse",
            "Cardigan",
            "Pajamas",
            "Overalls",
            "Boots",
            "Flip-Flops",
            "Tank Top",
            "Underwear",
            "Jumpsuit",
            "Windbreaker"
        ]
    },
    {
        "listTitle": "Games",
        "list": [
            "Chess",
            "Monopoly",
            "Scrabble",
            "Poker",
            "Uno",
            "Settlers of Catan",
            "Risk",
            "Clue",
            "Twister",
            "Jenga",
            "Card Games",
            "Tabletop RPGs",
            "Minesweeper",
            "Sudoku",
            "Trivia",
            "Bingo",
            "Video Games",
            "Darts",
            "Karaoke",
            "Pictionary",
            "Charades",
            "Ludo",
            "Go",
            "Backgammon",
            "Cribbage"
        ]
    },
    {
        "listTitle": "Cartoon Characters",
        "list": [
            "Mickey Mouse",
            "SpongeBob SquarePants",
            "Bugs Bunny",
            "Tom and Jerry",
            "Donald Duck",
            "Bart Simpson",
            "Scooby-Doo",
            "Popeye",
            "Daffy Duck",
            "Charlie Brown",
            "Pikachu",
            "Garfield",
            "Winnie the Pooh",
            "The Powerpuff Girls",
            "Dexter",
            "Stewie Griffin",
            "Finn the Human",
            "Wallace and Gromit",
            "Avatar Aang",
            "Shrek",
            "Dora the Explorer",
            "Hello Kitty",
            "Puss in Boots",
            "Stitch",
            "Yogi Bear"
        ]
    },
    {
        "listTitle": "Superheroes",
        "list": [
            "Superman",
            "Batman",
            "Spider-Man",
            "Wonder Woman",
            "Iron Man",
            "Captain America",
            "Thor",
            "Hulk",
            "Black Panther",
            "Deadpool",
            "Green Lantern",
            "Flash",
            "Aquaman",
            "Wolverine",
            "Daredevil",
            "Captain Marvel",
            "Green Arrow",
            "Ant-Man",
            "Black Widow",
            "Doctor Strange",
            "Nightwing",
            "Green Hornet",
            "The Flash",
            "Silver Surfer",
            "Batgirl",
            "Black Canary"
        ]
    },
    {
        "listTitle": "Body Parts",
        "list": [
            "Head",
            "Arm",
            "Leg",
            "Hand",
            "Foot",
            "Eye",
            "Ear",
            "Nose",
            "Mouth",
            "Back",
            "Knee",
            "Elbow",
            "Shoulder",
            "Wrist",
            "Ankle",
            "Chest",
            "Stomach",
            "Neck",
            "Finger",
            "Toe",
            "Brain",
            "Liver",
            "Lung",
            "Heart",
            "Kidney"
        ]
    },
    {
        "listTitle": "Household Items",
        "list": [
            "Chair",
            "Table",
            "Sofa",
            "Bed",
            "Lamp",
            "Television",
            "Refrigerator",
            "Oven",
            "Microwave",
            "Dishwasher",
            "Washing Machine",
            "Dryer",
            "Coffee Maker",
            "Blender",
            "Toaster",
            "Iron",
            "Vacuum Cleaner",
            "Curtains",
            "Rug",
            "Shelf",
            "Dishes",
            "Cutlery",
            "Pots",
            "Pans",
            "Mop"
        ]
    },
    {
        "listTitle": "Planets/Space Objects",
        "list": [
            "Earth",
            "Mars",
            "Jupiter",
            "Saturn",
            "Venus",
            "Mercury",
            "Uranus",
            "Neptune",
            "Pluto",
            "Asteroids",
            "Comets",
            "Galaxies",
            "Black Holes",
            "Stars",
            "Nebulae",
            "Satellites",
            "Moons",
            "Supernovae",
            "Quasars",
            "Space Stations",
            "Meteorites",
            "Dark Matter",
            "Dwarf Planets",
            "Space Probes",
            "Exoplanets"
        ]
    }
]

function shuffleArray(array) {
    for (let i = array.length - 1; i > 0; i--) {
        const j = Math.floor(Math.random() * (i + 1));
        [array[i], array[j]] = [array[j], array[i]];
    }
    return array;
}

// Function to get a random category and shorten the list to 25
function getRandomWordList() {
    // Pick a random category
    const randomCategoryIndex = Math.floor(Math.random() * wordLists.length);
    const selectedCategory = wordLists[randomCategoryIndex];

    // Shuffle the list within the category
    const shuffledList = shuffleArray([...selectedCategory.list]); // Use spread operator to avoid modifying the original array

    // Shorten the list to 25 items
    const shortenedList = shuffledList.slice(0, 25);

    return {
        listTitle: selectedCategory.listTitle,
        list: shortenedList
    };
}

// Get a random object
module.exports = {getRandomWordList}